### ISSUE TITLE
Implement sgn0 for SWU hash to curve and return the correct square root

### ISSUE THREAD

**Issue by drskalman** [w3f/arkworks-algebra#15]
we are returning y or -y randomly whatever arkwork square root function gives. The choice which square root to ruturn is y = Sgn0 (t).√fi (xj ). where

"Sgn0 (β) is a function that returns the “sign” of β. For β ∈ Fp , let
 Sgn0 (β) = −1 if β > (p − 1)/2, and 1 otherwise. For γ = γ0 + γ1√d ∈ Fp2 , Fp [√d]/(x2 − d), let Sgn0 (γ) = Sgn0 (γ1 ) if γ1 != 0, and Sgn0 (γ0 ) otherwise."

See Section 2 and 3 of

- Wahby, R. S., & Boneh, D. (2019). Fast and simple constant-time
  hashing to the bls12-381 elliptic curve. IACR Transactions on
  Cryptographic Hardware and Embedded Systems, nil(nil), 154–179.
  http://dx.doi.org/10.46586/tches.v2019.i4.154-179

**Comment by InaOana** [comment]
The ietf standard defines sgn0 for Fp2 (in their notation GF(p^2)) in https://tools.ietf.org/pdf/draft-irtf-cfrg-hash-to-curve-13.pdf, end of page 16.

**Comment by drskalman** [comment]
@InaOana  could you look into zcash/pasta code and is how did they implement is_odd for extension fields so we do the same in arkworks?

**Comment by InaOana** [comment]
@drskalman They have https://github.com/zcash/pasta_curves/blob/main/src/fields/fq.rs but I assume it's for prime fields.

**Comment by Pratyush** [comment]
I think my suggestion is compatible with the IETF standard; we can generalize the IETF impl to higher-degree extension fields. It might be worth emailing Riad also to ask his opinion on an appropriate generalization strategy.

**Comment by burdges** [comment]
cc @kwantam
