### ISSUE TITLE
Verify that the isogeny implemented for testing BLS12-381 is the same is in the standard

### ISSUE THREAD

**Issue by drskalman** [w3f/arkworks-algebra#39]
There are two isogenies of degree 11 from BLS12-381 to a SWU compatible curve. We should be using the same one that is chosen in the IETF draft standard.

**Comment by mmagician** [comment]
Yes, and for g2 too. The cofactor clearing and parity for g2 are still not giving the right results though, but I see q0 and q1 having the right x coordinate

**Comment by InaOana** [comment]
Are the coefficients for the ietf compatible isogeny (for G1) added on a public branch? I have just added them here https://github.com/w3f/arkworks-algebra/commit/6da5519e30250303fc92a1dcf837e37af1f53267

**Comment by mmagician** [comment]
Yea it's all here https://github.com/mmagician/algebra/tree/map-to-curve-tests
